version: '3.8'
services:
  angular:
    build: 
      context: ./frontend
    ports:
      - '4200:4200'
    depends_on:
      - nest
  nest:
    build: ./backend
    ports:
      - '3000:3000'
    environment:
      MYSQL_USER: backend
      MYSQL_PASSWORD: q1Q!q1Q!
      MYSQL_DATABASE: crud
    depends_on:
      - mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mysql
  mysql:
    image: mysql:latest
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: q1Q!q1Q!
      MYSQL_USER: backend
      MYSQL_PASSWORD: q1Q!q1Q!
      MYSQL_DATABASE: crud
    volumes:
      - ./medical_specialty.sql:/docker-entrypoint-initdb.d/medical_specialty.sql
